version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /root/fontend/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /root/fontend/node_modules
      - .:/app
    command: ["npm", "run", "test"]